timezone: "America/Toronto"
encoding: "utf-8"
permalink: "/:year/:month/:day/:title/"

name: "Beyond Technically Correct"
description: "Jeffrey Charles's technology blog"
url: "https://www.beyondtechnicallycorrect.com"

defaults:
  -
    scope:
      path: ""
    values:
      active: "entries"
      layout: "post"
